<a href="https://www.kaggle.com/code/mahabub001cs/numpy-class-5?scriptVersionId=346367044" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv


# Import libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [4]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [5]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# numpy array creation

In [6]:
[1,2,3]
# 1D array
x = np.array([1.23,2,3],dtype = float)
x

array([1.23, 2.  , 3.  ])

In [7]:
# 2D array
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 3D array
z = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
z

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
# arange for array creation
x = np.arange(0,100)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# reshape

In [10]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
# reshape the array
np.arange(81).reshape(3,3,3,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

# ones and zeros function

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# using random

In [15]:
np.round(np.random.random((3,5))*1000)

array([[257., 781.,  34., 670., 991.],
       [607., 792., 156., 503., 513.],
       [514., 919., 818., 467., 659.]])

# using linspace

In [16]:
np.linspace(10,100,20,dtype = int)

array([ 10,  14,  19,  24,  28,  33,  38,  43,  47,  52,  57,  62,  66,
        71,  76,  81,  85,  90,  95, 100])

# numpy array from dataframe

In [17]:
age = titanic['Age'].to_numpy()
print(age)

[22.   38.   26.   35.   35.     nan 54.    2.   27.   14.    4.   58.
 20.   39.   14.   55.    2.     nan 31.     nan 35.   34.   15.   28.
  8.   38.     nan 19.     nan   nan 40.     nan   nan 66.   28.   42.
   nan 21.   18.   14.   40.   27.     nan  3.   19.     nan   nan   nan
   nan 18.    7.   21.   49.   29.   65.     nan 21.   28.5   5.   11.
 22.   38.   45.    4.     nan   nan 29.   19.   17.   26.   32.   16.
 21.   26.   32.   25.     nan   nan  0.83 30.   22.   29.     nan 28.
 17.   33.   16.     nan 23.   24.   29.   20.   46.   26.   59.     nan
 71.   23.   34.   34.   28.     nan 21.   33.   37.   28.   21.     nan
 38.     nan 47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.
 21.     nan 32.5  32.5  54.   12.     nan 24.     nan 45.   33.   20.
 47.   29.   25.   23.   19.   37.   16.   24.     nan 22.   24.   19.
 18.   19.   27.    9.   36.5  42.   51.   22.   55.5  40.5    nan 51.
 16.   30.     nan   nan 44.   40.   26.   17.    1.    9.     nan 45.


In [18]:
data = titanic[['Age','Fare']].to_numpy()
data

array([[22.    ,  7.25  ],
       [38.    , 71.2833],
       [26.    ,  7.925 ],
       ...,
       [    nan, 23.45  ],
       [26.    , 30.    ],
       [32.    ,  7.75  ]])

In [19]:
data.shape

(891, 2)

# 3 different dimensional array (1D, 2D, 3D)

In [20]:
x = np.arange(10)
y = np.arange(12).reshape(3,4)
z = np.arange(27).reshape(3,3,3)

# np-array understanding

# 1. check dimension

In [21]:
x.ndim

1

In [22]:
y.ndim

2

In [23]:
z.ndim

3

# 2. shape of array

In [24]:
y.shape

(3, 4)

In [25]:
z.shape

(3, 3, 3)

# 3. size of data

In [26]:
np.size(x)

10

In [27]:
np.size(z)

27

In [28]:
np.size(data)

1782

# 4. memory occupied by item (byte)

In [29]:
x.itemsize

8

In [30]:
data.itemsize

8

In [31]:
# chance data type using astype
data = data.astype(np.float32)
data.itemsize

4

In [32]:
print(data.dtype)

float32


# arrary operation

In [33]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# 1. scalar operations

In [35]:
a * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [36]:
a ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# 2. vector operations

In [37]:
c = a + b
c

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [38]:
d = b - a
d

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [39]:
e = a * b
e

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Numpy function

In [40]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
age

array([22.  , 38.  , 26.  , 35.  , 35.  ,   nan, 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,   nan,
       31.  ,   nan, 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  ,   nan,
       19.  ,   nan,   nan, 40.  ,   nan,   nan, 66.  , 28.  , 42.  ,
         nan, 21.  , 18.  , 14.  , 40.  , 27.  ,   nan,  3.  , 19.  ,
         nan,   nan,   nan,   nan, 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  ,   nan, 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  ,   nan,   nan, 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  ,   nan,   nan,  0.83, 30.  , 22.  ,
       29.  ,   nan, 28.  , 17.  , 33.  , 16.  ,   nan, 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  ,   nan, 71.  , 23.  , 34.  ,
       34.  , 28.  ,   nan, 21.  , 33.  , 37.  , 28.  , 21.  ,   nan,
       38.  ,   nan, 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  ,   nan, 32.5 , 32.5 , 54.  , 12.  ,
         nan, 24.  ,

In [42]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
# axis = 0/1
# axis = 0 -> colum-wise
# axis = 1 -> row-wise

# 1. min/max

In [44]:
np.min(a, axis = 0)

array([0, 1, 2, 3])

In [45]:
np.max(a, axis = 1)

array([ 3,  7, 11])

In [46]:
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
np.min(z, axis = 1)

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

# sum

In [48]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.sum(x)

np.int64(45)

In [50]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
np.sum(y, axis = 0)

array([12, 15, 18, 21])

In [52]:
np.prod(y, axis = 1)

array([   0,  840, 7920])

In [53]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
np.mean(y, axis = 1)

array([1.5, 5.5, 9.5])

In [56]:
np.median(x)

np.float64(4.5)

In [57]:
np.median(y, axis = 1)

array([1.5, 5.5, 9.5])

# remove nan from age data

In [58]:
age

array([22.  , 38.  , 26.  , 35.  , 35.  ,   nan, 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,   nan,
       31.  ,   nan, 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  ,   nan,
       19.  ,   nan,   nan, 40.  ,   nan,   nan, 66.  , 28.  , 42.  ,
         nan, 21.  , 18.  , 14.  , 40.  , 27.  ,   nan,  3.  , 19.  ,
         nan,   nan,   nan,   nan, 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  ,   nan, 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  ,   nan,   nan, 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  ,   nan,   nan,  0.83, 30.  , 22.  ,
       29.  ,   nan, 28.  , 17.  , 33.  , 16.  ,   nan, 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  ,   nan, 71.  , 23.  , 34.  ,
       34.  , 28.  ,   nan, 21.  , 33.  , 37.  , 28.  , 21.  ,   nan,
       38.  ,   nan, 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  ,   nan, 32.5 , 32.5 , 54.  , 12.  ,
         nan, 24.  ,

In [59]:
new_age = ~np.isnan(age)

In [60]:
age = age[new_age]

# mean/max/mim/median age

In [61]:
np.mean(age)

np.float64(29.69911764705882)

In [62]:
np.min(age)

np.float64(0.42)

In [63]:
np.max(age)

np.float64(80.0)

In [64]:
np.median(age)

np.float64(28.0)

# std, var

In [65]:
np.std(age)

np.float64(14.516321150817316)

In [66]:
np.var(age)

np.float64(210.72357975366617)

# log, exp

In [67]:
# 10, 2, 50, 55,500000

In [68]:
# log for reducing distance between np elements
l = np.array([10000,50000, 500000000000])
np.log(l)

array([ 9.21034037, 10.81977828, 26.93787394])

In [69]:
# 0.001,0.22,0.458

In [70]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

# trigo

In [71]:
c

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [72]:
np.sin(c)

array([[-0.53657292,  0.99060736, -0.28790332, -0.75098725],
       [ 0.91294525, -0.00885131, -0.90557836,  0.76255845],
       [ 0.27090579, -0.98803162,  0.55142668,  0.52908269]])

# ceil, floor

In [73]:
# -1.8, -0.4, 1.3, 3.8

# floor -> -2, -1, 1, 3
# ceil -> -1, 0, 2, 4

arr = np.array([-1.8, -0.4, 1.3, 3.8])
print(np.floor(arr))
print(np.ceil(arr))

[-2. -1.  1.  3.]
[-1. -0.  2.  4.]


In [74]:
np.round(2.01455,2)

np.float64(2.01)

# indexing and slicing

In [75]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [78]:
x[4:7]

array([4, 5, 6])

In [79]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
y[:1,:]

array([[0, 1, 2, 3]])

In [81]:
y[1:2,2:4]

array([[6, 7]])

In [82]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
# 5,6
# 9,10

y[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [84]:
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
# z[matrix,row,colum]

In [86]:
z[0,1:2,:]

array([[3, 4, 5]])

In [87]:
z[1,1:2,:]

array([[12, 13, 14]])

In [88]:
z[:2,1:2,1:3]

array([[[ 4,  5]],

       [[13, 14]]])

In [89]:
z[0:2,1:2,1:3]

array([[[ 4,  5]],

       [[13, 14]]])

In [90]:
z[1,1:3,1:3]

array([[13, 14],
       [16, 17]])

# reshaping

In [91]:
d = np.arange(20).reshape(4,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [93]:
d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# stacking

In [95]:
d = np.arange(16).reshape(4,4)
e = np.arange(17,33).reshape(4,4)

In [96]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
e

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [98]:
# connect horizontally
np.hstack((e,d))

array([[17, 18, 19, 20,  0,  1,  2,  3],
       [21, 22, 23, 24,  4,  5,  6,  7],
       [25, 26, 27, 28,  8,  9, 10, 11],
       [29, 30, 31, 32, 12, 13, 14, 15]])

In [99]:
# connect vertically
np.vstack((d,e,d))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# spliting

In [100]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
np.hsplit(d,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [102]:
np.vsplit(e,4)

[array([[17, 18, 19, 20]]),
 array([[21, 22, 23, 24]]),
 array([[25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]